version: "3"

services:
  pocketurlapi:
    build: api
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
    depends_on:
      - postgresdb
      - redisdb

  postgresdb:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pocketurl
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redisdb:
    build: db
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: anchit1909@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password123
    depends_on:
      - postgresdb
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - default

volumes:
  postgres_data:
  redis_data:
  pgadmin-data:
